/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chriscarini.jetbrains.diagnostic.reporter;

import org.junit.Test;
import static org.junit.Assert.*;

public class CariniLibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        CariniLibrary classUnderTest = new CariniLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
